# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TamBoonExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TamBoonExample

  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Kingfisher', '~> 5.0'

  target 'TamBoonExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TamBoonExampleUITests' do
    # Pods for testing
  end

end
